# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/docker/docker"
  version = "v17.05.0-ce"

# Force docker/distribution to match what docker/docker had as a dependency:
# https://github.com/moby/moby/blob/v17.05.0-ce/vendor.conf#L48:32
[[constraint]]
  name = "github.com/docker/distribution"
  revision = "b38e5838b7b2f2ad48e06ec4b500011976080621"

[[constraint]]
  name = "github.com/src-d/go-git"
  version = "4.3.1"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.3.1"

[prune]
  go-tests = true
  unused-packages = true
