# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/docker/docker"
  revision = "b963b55a8a3fec0e97feeb07427a91e29c870284"

# Force docker/distribution to match what docker/docker has as a dependency:
# https://github.com/moby/moby/blob/b963b55/vendor.conf#L62
[[constraint]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

# Force sirupsen/logrus to match what docker/docker has as a dependency:
# https://github.com/moby/moby/blob/b963b55/vendor.conf#L13
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

# Force prometheus/client_golang to match v0.9.0-pre1, which contains the below type:
#
# > $ git log --pretty=oneline -S"type Observer interface"
# > d01fd6222241828327e3507d64c90f796673bad0 new handler instrumentation (#285)
# > 8496756f6dba0a23a5fde5bd986f4e3233e55ef6 Turn timer helper into a struct with methods
#
# > $ git tag --contains 8496756f6dba0a23a5fde5bd986f4e3233e55ef6
# > v0.9.0-pre1
#
# as otherwise, the build fails with:
# > # github.com/weaveworks-experiments/imagediff/vendor/github.com/docker/go-metrics
# > vendor/github.com/docker/go-metrics/timer.go:39:4: undefined: prometheus.Observer
#
[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.0-pre1"

[[constraint]]
  name = "github.com/src-d/go-git"
  version = "4.3.1"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.3.1"

[prune]
  go-tests = true
  unused-packages = true
